import type { CalendarEvent } from "@/app/components/calendar/types"

export const mockEvents: CalendarEvent[] = [
  {
    id: "1",
    date: 5,
    title: "Aspirina 500mg",
    time: "08:00",
    type: "medicine",
    description: "Tomar con agua después del desayuno",
    status: "success",
    retries: 0,
    maxRetries: 2,
    contactMethod: "whatsapp",
    duration: 15,
  },
  {
    id: "2",
    date: 5,
    title: "Metformina",
    time: "12:00",
    type: "medicine",
    description: "Tomar durante la comida",
    status: "pending",
    retries: 1,
    maxRetries: 2,
    contactMethod: "call",
    duration: 15,
  },
  {
    id: "3",
    date: 8,
    title: "Cita con Dr. García",
    time: "10:30",
    type: "appointment",
    description: "Revisión cardiólogo - Consultorio 2B",
  },
  {
    id: "4",
    date: 12,
    title: "Atorvastatina",
    time: "20:00",
    type: "medicine",
    description: "Tomar antes de dormir",
    status: "failed",
    retries: 2,
    maxRetries: 2,
    contactMethod: "whatsapp",
    duration: 15,
  },
  {
    id: "5",
    date: 15,
    title: "Laboratorio",
    time: "09:00",
    type: "appointment",
    description: "Análisis de sangre - Clinica San Pedro",
  },
  {
    id: "6",
    date: 22,
    title: "Insulina",
    time: "07:00",
    type: "medicine",
    description: "Inyección subcutánea",
    status: "success",
    retries: 0,
    maxRetries: 2,
    contactMethod: "call",
    duration: 15,
  },
]
