import { Reminder, ReminderInstance } from "./types"

export const mockReminders: Reminder[] = [
  {
    id: 1,
    reminder_type: "medicine",
    periodicity: "Cada 8 horas",
    start_date: "2024-01-01",
    end_date: "2024-12-31",
    is_active: true,
    medicine: {
      id: 1,
      name: "Aspirina",
      dosage: "500mg",
      total_tablets: 60,
      tablets_left: 42,
      tablets_per_dose: 1,
      notes: "Tomar con comida",
    },
    executions: [
      {
        id: 1,
        executed_at: "2024-11-22 08:00",
        status: "success",
        method: "whatsapp",
        retries: 0,
        duration_minutes: 2,
      },
      { id: 2, executed_at: "2024-11-22 16:00", status: "success", method: "call", retries: 1, duration_minutes: 5 },
      {
        id: 3,
        executed_at: "2024-11-23 00:00",
        status: "failed",
        method: "whatsapp",
        retries: 3,
        duration_minutes: 15,
      },
    ],
  },
  {
    id: 2,
    reminder_type: "medicine",
    periodicity: "Cada 12 horas",
    start_date: "2024-01-15",
    end_date: null,
    is_active: true,
    medicine: {
      id: 2,
      name: "Insulina",
      dosage: "10 unidades",
      total_tablets: 30,
      tablets_left: 8,
      tablets_per_dose: 1,
      notes: "Aplicar antes de las comidas",
    },
    executions: [
      {
        id: 4,
        executed_at: "2024-11-22 07:00",
        status: "success",
        method: "whatsapp",
        retries: 0,
        duration_minutes: 1,
      },
      {
        id: 5,
        executed_at: "2024-11-22 19:00",
        status: "success",
        method: "whatsapp",
        retries: 0,
        duration_minutes: 3,
      },
    ],
  },
  {
    id: 3,
    reminder_type: "medicine",
    periodicity: "Diario",
    start_date: "2024-02-01",
    end_date: "2024-06-30",
    is_active: false,
    medicine: {
      id: 3,
      name: "Omeprazol",
      dosage: "20mg",
      total_tablets: 30,
      tablets_left: 0,
      tablets_per_dose: 1,
      notes: "En ayunas",
    },
    executions: [],
  },
]

export const mockReminderInstances: ReminderInstance[] = [
  {
    id: 1,
    reminder_id: 1,
    scheduled_datetime: "2024-11-22 08:00",
    status: "success",
    taken_at: "2024-11-22 08:05",
    retry_count: 0,
    max_retries: 3,
    method: "whatsapp",
    medicine_name: "Aspirina",
    dosage: "500mg",
  },
  {
    id: 2,
    reminder_id: 1,
    scheduled_datetime: "2024-11-22 16:00",
    status: "failed",
    taken_at: null,
    retry_count: 3,
    max_retries: 3,
    method: "call",
    medicine_name: "Aspirina",
    dosage: "500mg",
  },
  {
    id: 3,
    reminder_id: 2,
    scheduled_datetime: "2024-11-22 19:00",
    status: "success",
    taken_at: "2024-11-22 19:02",
    retry_count: 1,
    max_retries: 3,
    method: "whatsapp",
    medicine_name: "Insulina",
    dosage: "10 unidades",
  },
  {
    id: 4,
    reminder_id: 1,
    scheduled_datetime: "2024-11-22 23:59",
    status: "pending",
    taken_at: null,
    retry_count: 0,
    max_retries: 3,
    method: "whatsapp",
    medicine_name: "Aspirina",
    dosage: "500mg",
  },
]
